front/protected/controllers/SiteController.php
<?php

class SiteController extends Controller {

    /**
     * Declares class-based actions.
     */
    public $rutaImagen;
    public $rutaSlide;

    /*
     * Construccion ruta de bodega de imagenes
     */

    public function init() {
//        if (Yii::app()->user->isguest) {
//            $this->redirect(array('/site/login'));
//        }
        $scriptDir = "";
        $this->rutaImagen = $scriptDir . Yii::app()->params['imagePath'] . "/";
        $this->rutaSlide = "mi-ruta/";
        parent::init();
    }

    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {
        $promo = Promocion::model()->findAll();
        $this->pageTitle = YII::app()->name;
        $criteria = new CDbCriteria;
        $criteria->addCondition('id_estado_producto = 1');
        $criteria->addCondition('cantidad_producto > 0');
        $criteria->order = 'RAND()';
        $criteria->limit = 9;

        $productos = Producto::model()->findAll($criteria);
        $this->render('index', array("promo" => $promo, "productos" => $productos));
    }

    public function actionTerminos() {
        $this->pageTitle = "Terminos y condiciones" . " - " . YII::app()->name;
        $this->render('terminos');
    }

    public function actionPrivacidad() {
        $this->pageTitle = "Privacidad" . " - " . YII::app()->name;
        $this->render('privacidad');
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /*
     * Accion para envio de correo y recordar contraseña
     */

    public function actionRecordarpass() {
        $this->pageTitle = "Recordar contraseña" . " - " . YII::app()->name;

        $model = new Cliente('recordar');

        if (isset($_POST['Cliente']['correo_cliente'])) {
            $correo = $_POST['Cliente']['correo_cliente'];
            $model->attributes = $_POST['Cliente'];

            $model->validate("correo_cliente");

            $criteria = new CDbCriteria;
            $criteria->addCondition("correo_cliente = '" . $model->correo_cliente . "'");
            $criteria->addCondition('id_estado_usuario = 1');
            $envio = Cliente::model()->find($criteria);

            if ($envio) {
                $link = Yii::app()->createAbsoluteUrl("site/reset", array("m" => md5($envio->correo_cliente)));

                $message = '<p>Para restablecer su contraseña <a href="' . $link . '">Clic Aquí</a></p>';

                if ($_SERVER["SERVER_NAME"] == "localhost") {
                    dump($message);
                    Yii::app()->user->setFlash('warning', '<p>El sistema esta instalado en una maquina local y no se envia correo. </p>' . $message);
                } else {
                    $headers = "From: {" . Yii::app()->params['adminEmail'] . "}\r\nReply-To: {" . Yii::app()->params['adminEmail'] . "}";
                    mail($envio->correo_cliente, "Recuperar contraseña", $message, $headers);
                }
            } else {
                Yii::app()->user->setFlash('error', 'El correo no se encuentra registrado');
            }
        }
        $this->render('recordar', array("model" => $model));
    }

    public function actionReset() {
        $this->pageTitle = "Recuperar contraseña - " . YII::app()->name;

        $m = $_GET["m"];
        $clientes = Cliente::model()->findAll();
        foreach ($clientes as $value) {
            if (md5($value->correo_cliente) == $m) {
                $id_cliente = $value->id_cliente;
                $model = Cliente::model()->findByPk($id_cliente);
                $model->contrasena_cliente = "";
                if (isset($_POST['Cliente'])) {
                    $model->attributes = $_POST['Cliente'];
                    if ($model->contrasena_cliente === $model->repetir_contrasena) {
                        $model->contrasena_cliente = md5($model->contrasena_cliente);
                        if ($model->save()) {
                            Yii::app()->user->setFlash('success', "Se actualizaron los datos correctamente");
                            $this->redirect(array('site/login'));
                        }
                    } else {
                        Yii::app()->user->setFlash('error', "Las contraseñas no coinciden");
                        $this->render('reset', array("model" => $model));
                    }
                } else {
                    $this->render('reset', array("model" => $model));
                }
                break;
            }
        }
//        $this->render('reset');
    }

    /**
     * Displays the contact page
     */
    public function actionContact() {
        $model = new ContactForm;
        if (isset($_POST['ContactForm'])) {
            $model->attributes = $_POST['ContactForm'];
            if ($model->validate()) {
                $identificacionemail = "<p>" . $model->body . "</p>";

                $headers = "From: {$model->email}\r\nReply-To: {$model->email}";
                mail(Yii::app()->params['adminEmail'], $model->subject, $model->body, $headers);
                Yii::app()->user->setFlash('contact', 'Thank you for contacting us. We will respond to you as soon as possible.');
                $this->refresh();
            }
        }
        $this->render('contact', array('model' => $model));
    }

    public function actionRegistro() {
        $model = new Cliente('registro');
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Cliente'])) {
            $fecha = date_create()->format('Y-m-d H:i:s');
            $model->attributes = $_POST['Cliente'];
            $model->contrasena_cliente = md5($model->contrasena_cliente);
            $model->fecha_creacion_cliente = $fecha;
            $model->id_estado_usuario = 1;
            if ($model->save()) {
                $this->redirect(array('login', 'id' => $model->id_cliente));
            }
        }
        $model->contrasena_cliente = "";
        $this->render('registro', array(
            'model' => $model,
        ));
    }

    /**
     * Displays the login page
     */
    public function actionLogin() {
        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login()) {
                if (isset($_GET[0]['r'])) {
                    $return = $_GET[0]['r'];
                    $this->redirect($return);
                } else {
                    $this->redirect(Yii::app()->user->returnUrl);
                }
//                $this->redirect($current);
            }
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }

    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'cliente-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

front/protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="col-1-content" class="row">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

front/protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

front/protected/views/layouts/main.php
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.min.js"></script>
        <!-- Custom Theme files -->

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous"/>
        <!-- Tema opcional -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous"/>
        <!-- JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
        <!--fonts-->
        <link href='http://fonts.googleapis.com/css?family=Libre+Baskerville:400,700,400italic' rel='stylesheet' type='text/css' />
        <link href='http://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css' />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css' />
        <!--//fonts-->

        <link href="<?php echo Yii::app()->request->baseUrl; ?>/css/style.css" rel="stylesheet" type="text/css" media="all" />	
        <link href="<?php echo Yii::app()->request->baseUrl; ?>/css/complemento.css" rel="stylesheet" type="text/css" media="all" />	
    </head>
    <body> 
        <!--header-->
        <div class="header">
            <div class="header-top  navbar-fixed-top">
                <div class="container">
                    <div class="header-gridd col-lg-6 col-md-6 col-sm-12 text-right pull-right">
                        <?php $this->widget('UserLoginForm', array("id"=>"loginform")); ?>
                    </div>

                    <div class="clearfix"> </div>
                </div>
            </div>
            
            <div class="container" style="margin-top: 100px;">
                <div class="header-bottom">			
                    <div class="logo">
                        <a href="<?php echo Yii::app()->controller->createUrl("site/index"); ?>">
                            <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/Logo/2logo.png" class="img-fluid" style="height: auto; width: 100%" />
                        </a>
                    </div>
                    <div class="ad-right">

                    </div>
                    <div class="clearfix"> </div>
                </div>	
                <?php $this->widget('Menu', array("tipo" => "top")); ?> 
            </div>
        </div>
        <!--content-->

            <div class="container">
                <?php echo $content; ?>
            </div>
        <!---->
        <div class="footer">
            <div class="container">
                <div class="footer-class">
                    <div class="class-footer">
                        <ul>
                            <li><a href="<?php echo Yii::app()->controller->createUrl("site/index"); ?>" class="scroll">Inicio </a><label>|</label></li>
                            <li><a href="<?php echo Yii::app()->controller->createUrl("site/terminos"); ?>" class="scroll">Terminos y condiciones</a><label>|</label></li>
                            <li><a href="<?php echo Yii::app()->controller->createUrl("site/privacidad"); ?>" class="scroll">Privacidad</a><label>|</label></li>
                            <li><a href="<?php echo Yii::app()->controller->createUrl("site/contact"); ?>" class="scroll">Contacto </a></li>
                        </ul>
                        <p class="footer-grid">&copy; 2018 Derechos Reservados  #ADSI-150 </p>
                    </div>	 
                    <div class="footer-left">
                        <a href="<?php echo Yii::app()->controller->createUrl("site/index"); ?>">
                            <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/Logo/3logo.png" class="img-fluid" style="height: auto; width: 100%"/>
                        </a>
                    </div> 
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
        <script>
            $(document).ready(function () {
                $('.add-to-cart').click(function () {
                    var data = [];
                    data = {'id': $(this).data('id'), 'nomProducto': $(this).data('nombre')};
                    $.post('<?= Yii::app()->controller->createUrl("productos/SetProduct") ?>', data, function (response) {
                        //swal( 'Agregado!', 'Se agrego! '+data.nomProducto, 'success' );
                        alert("Elemento agregado: " + data.nomProducto);
                        $('.contcarr').html(response);

                    });
                    return false;
                });
            });
        </script>
    </body>
</html>