front/protected/models/Usuario.php
<?php

/**
 * This is the model class for table "tbl_usuario".
 *
 * The followings are the available columns in table 'tbl_usuario':
 * @property integer $id_usuario
 * @property string $nombre_usuario
 * @property string $apellido_usuario
 * @property string $nick_user
 * @property string $correo_usuario
 * @property string $contrasena_usuario
 * @property string $fecha_creacion_usuario
 * @property string $imagen_usuario
 * @property integer $id_estado_usuario
 * @property integer $id_tipo_usuario
 *
 * The followings are the available model relations:
 * @property TblFactura[] $tblFacturas
 * @property TblOrdenCompra[] $tblOrdenCompras
 * @property TblEstadoUsuario $idEstadoUsuario
 * @property TblTipoUsuario $idTipoUsuario
 */
class Usuario extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Usuario the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_usuario';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nombre_usuario, apellido_usuario, nick_user, correo_usuario, contrasena_usuario, fecha_creacion_usuario, id_estado_usuario, id_tipo_usuario', 'required'),
			array('id_estado_usuario, id_tipo_usuario', 'numerical', 'integerOnly'=>true),
			array('nombre_usuario, apellido_usuario, nick_user', 'length', 'max'=>50),
			array('correo_usuario', 'length', 'max'=>60),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			
			array('id_usuario, nombre_usuario, apellido_usuario, nick_user, correo_usuario, contrasena_usuario, fecha_creacion_usuario, imagen_usuario, id_estado_usuario, id_tipo_usuario', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'tblFacturas' => array(self::HAS_MANY, 'TblFactura', 'id_usuario'),
			'tblOrdenCompras' => array(self::HAS_MANY, 'TblOrdenCompra', 'id_usuario'),
			'idEstadoUsuario' => array(self::BELONGS_TO, 'TblEstadoUsuario', 'id_estado_usuario'),
			'idTipoUsuario' => array(self::BELONGS_TO, 'TblTipoUsuario', 'id_tipo_usuario'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id_usuario' => 'Id Usuario',
			'nombre_usuario' => 'Nombre Usuario',
			'apellido_usuario' => 'Apellido Usuario',
			'nick_user' => 'Nick User',
			'correo_usuario' => 'Correo Usuario',
			'contrasena_usuario' => 'Contrasena Usuario',
			'fecha_creacion_usuario' => 'Fecha Creacion Usuario',
			'imagen_usuario' => 'Imagen Usuario',
			'id_estado_usuario' => 'Id Estado Usuario',
			'id_tipo_usuario' => 'Id Tipo Usuario',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id_usuario',$this->id_usuario);
		$criteria->compare('nombre_usuario',$this->nombre_usuario,true);
		$criteria->compare('apellido_usuario',$this->apellido_usuario,true);
		$criteria->compare('nick_user',$this->nick_user,true);
		$criteria->compare('correo_usuario',$this->correo_usuario,true);
		$criteria->compare('contrasena_usuario',$this->contrasena_usuario,true);
		$criteria->compare('fecha_creacion_usuario',$this->fecha_creacion_usuario,true);
		$criteria->compare('imagen_usuario',$this->imagen_usuario,true);
		$criteria->compare('id_estado_usuario',$this->id_estado_usuario);
		$criteria->compare('id_tipo_usuario',$this->id_tipo_usuario);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

front/protected/controllers/UsuarioController.php
<?php

class UsuarioController extends Controller {

    public $rutaImagen;



    public function accessRules() {
        return array(array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array(''),
                'users' => array('*')),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('index', 'pass', 'compras'),
                'users' => array('@')),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('index', 'pass', 'compras'),
                'users' => array('admin')),
            array('deny', // deny all users
                'users' => array('*')));
    }

    public function init() {
        if (Yii::app()->user->isGuest) {
            $this->redirect(array('/site/index'));
        }

        $scriptDir = "";
        $this->rutaImagen = $scriptDir . Yii::app()->params['imagePath']. "/";
        parent::init();
    }

    public function actionIndex() {
        $this->pageTitle = "Mi cuenta - ".YII::app()->name;
        $model = Cliente::model()->findByPk(Yii::app()->user->id);
        if (isset($_POST['Cliente'])) {
            $model->attributes = $_POST['Cliente'];
            if ($model->save()) {
                Yii::app()->user->setFlash('success', "Se actualizaron los datos correctamente");
//                $this->redirect(array('view', 'id' => $model->id_cliente));
            }
        }
        $this->render('index', array("model" => $model));
    }

    public function actionPass() {
        $this->pageTitle = "Cambiar contraseña - ".YII::app()->name;
        $model = Cliente::model()->findByPk(Yii::app()->user->id);
        $model->contrasena_cliente = "";
        if (isset($_POST['Cliente'])) {
            $model->attributes = $_POST['Cliente'];
            if ($model->contrasena_cliente === $model->repetir_contrasena) {
                $model->contrasena_cliente= md5($model->contrasena_cliente);
                if ($model->save()) {
                    Yii::app()->user->setFlash('success', "Se actualizaron los datos correctamente");
//                $this->redirect(array('view', 'id' => $model->id_cliente));
                }
            }else{
                Yii::app()->user->setFlash('error', "Las contraseñas no coinciden");
            }
        }

        $this->render('password', array("model" => $model));
    }
    
    public function actionCompras() {
        $this->pageTitle = "Mis compras - ".YII::app()->name;
//        $model = Factura::model()->findByPk(Yii::app()->user->id);
        
        $dataProvider = new CActiveDataProvider('Factura', array(
            'criteria' => array(
                'condition' => 'id_cliente=' . Yii::app()->user->id,
                'order' => 'id_factura ASC',
            ),
            'pagination' => array(
                'pageSize' => 12,
            ),
        ));
        
        $this->render('compras', array("dataProvider" => $dataProvider));
    }
    
    public function actionDetalleFactura($id) {
        $this->pageTitle = "Detalle de compra #".$id." - ".YII::app()->name;
        $model = Factura::model()->findByPk($id);
        $detalle = DetalleFactura::model()->findAll("id_factura=".$id);
        $this->render('detallefactura', array("model" => $model, "detalle"=>$detalle));
    }


}

front/protected/views/usuario/_datosusuario.php
<div class="col-md-12">
    <h2>Mis datos</h2>
    <?php if (Yii::app()->user->hasFlash('success')): ?>
        <div class="alert alert-success fade in alert-dismissible" style="margin-top:18px;">
            <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
            <?php echo Yii::app()->user->getFlash('success'); ?>
        </div>
    <?php endif; ?>
</div>

    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'cliente-form',
        'enableAjaxValidation' => false,
    ));
    ?>


    <?php echo $form->errorSummary($model); ?>

    <div class="col-md-12">
        <?php echo $form->labelEx($model, 'document_cliente'); ?>
        <?php echo $form->textField($model, 'document_cliente', array('size' => 50, 'maxlength' => 50, 'class' => "form-control")); ?>
        <?php echo $form->error($model, 'document_cliente'); ?>
    </div>

    <div class="col-md-12">
        <?php echo $form->labelEx($model, 'id_tipo_documento'); ?>
        <?php echo $form->dropDownList($model, 'id_tipo_documento', CHtml::listData(TipoDocumento::model()->findAll(), 'id_tipo_documento', 'nombre_tipo_documento'), array('empty' => 'Tipo de documento', 'class' => "form-control")); ?>
        <?php echo $form->error($model, 'id_tipo_documento'); ?>
    </div>

    <div class="col-md-12">
        <?php echo $form->labelEx($model, 'empresa_cliente'); ?>
        <?php echo $form->textField($model, 'empresa_cliente', array('size' => 50, 'maxlength' => 50, 'class' => "form-control")); ?>
        <?php echo $form->error($model, 'empresa_cliente'); ?>
    </div>

    <div class="col-md-12">
        <?php echo $form->labelEx($model, 'nombre_repre_cliente'); ?>
        <?php echo $form->textField($model, 'nombre_repre_cliente', array('size' => 50, 'maxlength' => 50, 'class' => "form-control")); ?>
        <?php echo $form->error($model, 'nombre_repre_cliente'); ?>
    </div>

    <div class="col-md-12">
        <?php echo $form->labelEx($model, 'apellido_repre_cliente'); ?>
        <?php echo $form->textField($model, 'apellido_repre_cliente', array('size' => 50, 'maxlength' => 50, 'class' => "form-control")); ?>
        <?php echo $form->error($model, 'apellido_repre_cliente'); ?>
    </div>

    <div class="col-md-12">
        <?php echo $form->labelEx($model, 'telefono_cliente'); ?>
        <?php echo $form->textField($model, 'telefono_cliente', array('size' => 50, 'maxlength' => 50, 'class' => "form-control")); ?>
        <?php echo $form->error($model, 'telefono_cliente'); ?>
    </div>

    <div class="col-md-12">
        <?php echo $form->labelEx($model, 'direccion_cliente'); ?>
        <?php echo $form->textField($model, 'direccion_cliente', array('size' => 50, 'maxlength' => 50, 'class' => "form-control")); ?>
        <?php echo $form->error($model, 'direccion_cliente'); ?>
    </div>

    <div class="col-md-12">
        <?php echo $form->labelEx($model, 'correo_cliente'); ?>
        <?php echo $form->textField($model, 'correo_cliente', array('size' => 50, 'maxlength' => 50, 'class' => "form-control")); ?>
        <?php echo $form->error($model, 'correo_cliente'); ?>
    </div>




    <div class="col-md-12">
        <?php echo $form->labelEx($model, 'id_ciudad'); ?>
        <?php echo $form->dropDownList($model, 'id_ciudad', CHtml::listData(Ciudad::model()->findAll(), 'id_ciudad', 'nombre_ciudad'), array('empty' => 'Seleccione ciudad', 'class' => "form-control")); ?>
        <?php echo $form->error($model, 'id_ciudad'); ?>
    </div>

    <div class="col-md-12 buttons">
        <?php echo CHtml::submitButton('Guardar', array("class" => "btn btn-success ")); ?>
    </div>

    <?php $this->endWidget(); ?>

front/protected/views/usuario/_facturas.php
<tr>
    <th scope="row">
        <a href="<?= Yii::app()->controller->createUrl("usuario/DetalleFactura", array("id" => $data->id_factura)) ?>">
            <?= $data->id_factura ?></a>
    </th>

    
    <td>
        <a href="<?= Yii::app()->controller->createUrl("usuario/DetalleFactura", array("id" => $data->id_factura)) ?>"><?= Helper::separarMiles($data->total_factura); ?></a>
    </td>
    <td><a class="btn btn-info" href="<?= Yii::app()->controller->createUrl("usuario/DetalleFactura", array("id" => $data->id_factura)) ?>" >Ver</a></td>

</tr>

front/protected/views/usuario/_menu_cuenta.php
<h1 class="">Mi cuenta</h1>
        <ul>
            <li><a href="<?=Yii::app()->controller->createUrl("usuario/index")?>"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Mis datos</a></li>
            <li><a href="<?=Yii::app()->controller->createUrl("usuario/pass")?>"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span> Cambiar contraseña</a></li>
            <li><a href="<?=Yii::app()->controller->createUrl("usuario/compras")?>"><span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span> Mis compras</a></li>
        </ul>

front/protected/views/usuario/compras.php
<div class="row">
    <div id="micuenta" class="container">
        <div id="" class="col-md-3 micuenta">
            <?php $this->renderPartial("_menu_cuenta"); ?>
        </div>
        <div class="col-md-9">
            <h2>Mis compras</h2>
            <div class="clearfix">
                <table class="table table-striped table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <td>#</td>
                            <td>Valor</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    $this->widget('zii.widgets.CListViewmm', array(
                        'id' => 'itemsListaFacturas',
                        'dataProvider' => $dataProvider,
                        'itemView' => '_facturas',
                        'ajaxUpdate' => false,
                        'template' => "{pager}\n{items}",
                        'cssFile' => false,
                        'htmlOptions' => array('class' => "clistWidgetView")
                    ));
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

front/protected/views/usuario/detallefactura.php
<div class="row">
    <div id="micuenta" class="container">
        <div id="" class="col-md-3 micuenta">
            <?php $this->renderPartial("_menu_cuenta"); ?>
        </div>
        <div class="col-md-9">
            <h2>Detalle compra # <?= $model->id_dian_factura ?></h2>
            <div class="clearfix">
                <table class="table table-striped table-bordered table-hover table-condensed text-left">
                    <thead class="thead-dark">
                        <tr>
                            <td>Item</td>
                            <td>Cantidad</td>
                            <td>Valor</td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $data = json_decode($model->detalle_factura);
                        $datoid = base64_encode($model->id_factura);
//                       dump($model);
                        foreach ($data as $key => $item ) {
                            echo "<tr>
                            <td>" . $item->descripcion . "</td>
                            <td>" . $item->cantidad . "</td>
                            <td>" . Helper::separarMiles($item->total) . "</td>
                            
                        </tr>";
                        }
                        ?>
                    </tbody>
                </table>
            <div class="container">
                <div class="row">
                <div class="col-sm-5">
                <p style="valor"><strong>Total impuesto:</strong><?=  Helper::separarMiles($model->iva_factura) ?></p>
                <p style="valor"><strong>Total compra:</strong> <?= Helper::separarMiles($model->total_factura) ?></p>
                </div>

                <div class="col-md-1 col-md-offset-2"><button class="btn btn-info btnImprimirFactura" ><span class="glyphicon glyphicon-print" aria-hidden="true"></span>
                      </button></div>

                
                </div>
            </div>       
            </div>
        </div>
    </div>

</div>

<script>
$('.btnImprimirFactura').click(function () {
            var data = '<?php echo $datoid;?>';
            
            window.open("<?php echo Yii::app()->request->baseUrl."/".$this->rutaImagen."../sis/extensiones/tcpdf/pdf/factura.php?codigo="; ?>"+data);

        });
</script>

front/protected/views/usuario/index.php
<div class="row">
    <div id="micuenta" class="container">
    <div id="" class="col-md-3 micuenta">
        <?php $this->renderPartial("_menu_cuenta"); ?>
    </div>
    <div class="col-md-9">
        <?php $this->renderPartial("_datosusuario", array("model" => $model)); ?>
    </div>
</div>

</div>

front/protected/views/usuario/password.php
<div class="row">
    <div id="micuenta" class="container">
        <div class="col-md-3 micuenta">
            <h1>Mi cuenta</h1>
            <ul>
                <li><a href="<?= Yii::app()->controller->createUrl("usuario/index") ?>"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Mis datos</a></li>
                <li><a href="<?= Yii::app()->controller->createUrl("usuario/pass") ?>"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span> Cambiar contraseña</a></li>
                <li><a href="<?= Yii::app()->controller->createUrl("usuario/compras") ?>"><span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span> Mis compras</a></li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="col-md-12">
                <h2>Cambiar contraseña</h2>
                <?php if (Yii::app()->user->hasFlash('success')): ?>
                    <div class="alert alert-success fade in alert-dismissible" style="margin-top:18px;">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                        <?php echo Yii::app()->user->getFlash('success'); ?>
                    </div>
                <?php endif; ?>
                <?php if (Yii::app()->user->hasFlash('error')): ?>
                    <div class="alert alert-warning fade in alert-dismissible" style="margin-top:18px;">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                        <?php echo Yii::app()->user->getFlash('error'); ?>
                    </div>
                <?php endif; ?>
            </div>
            <?php
            $form = $this->beginWidget('CActiveForm', array(
                'id' => 'cliente-form',
                'enableAjaxValidation' => false,
            ));
            ?>


            <?php echo $form->errorSummary($model); ?>

            <div class="col-md-12">
                <?php echo $form->labelEx($model, 'contrasena_cliente'); ?>
                <?php echo $form->passwordField($model, 'contrasena_cliente', array('size' => 50, 'maxlength' => 50, 'class' => "form-control")); ?>
                <?php echo $form->error($model, 'contrasena_cliente'); ?>
            </div>

            <div class="col-md-12">
                <?php echo $form->labelEx($model, 'repetir_contrasena'); ?>
                <?php echo $form->passwordField($model, 'repetir_contrasena', array('size' => 50, 'maxlength' => 50, 'class' => "form-control")); ?>
                <?php echo $form->error($model, 'repetir_contrasena'); ?>
            </div>

            <div class="col-md-12 buttons" style="margin-bottom: 5px">
                <?php echo CHtml::submitButton('Cambiar', array("class" => "btn btn-success ")); ?>
            </div>


            <?php $this->endWidget(); ?>
        </div>
    </div>

</div>