front/protected/controllers/SiteController.php
<?php

class SiteController extends Controller {

    /**
     * Declares class-based actions.
     */
    public $rutaImagen;
    public $rutaSlide;

    /*
     * Construccion ruta de bodega de imagenes
     */

    public function init() {
//        if (Yii::app()->user->isguest) {
//            $this->redirect(array('/site/login'));
//        }
        $scriptDir = "";
        $this->rutaImagen = $scriptDir . Yii::app()->params['imagePath'] . "/";
        $this->rutaSlide = "mi-ruta/";
        parent::init();
    }

    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {
        $promo = Promocion::model()->findAll();
        $this->pageTitle = YII::app()->name;
        $criteria = new CDbCriteria;
        $criteria->addCondition('id_estado_producto = 1');
        $criteria->addCondition('cantidad_producto > 0');
        $criteria->order = 'RAND()';
        $criteria->limit = 9;

        $productos = Producto::model()->findAll($criteria);
        $this->render('index', array("promo" => $promo, "productos" => $productos));
    }

    public function actionTerminos() {
        $this->pageTitle = "Terminos y condiciones" . " - " . YII::app()->name;
        $this->render('terminos');
    }

    public function actionPrivacidad() {
        $this->pageTitle = "Privacidad" . " - " . YII::app()->name;
        $this->render('privacidad');
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /*
     * Accion para envio de correo y recordar contraseña
     */

    public function actionRecordarpass() {
        $this->pageTitle = "Recordar contraseña" . " - " . YII::app()->name;

        $model = new Cliente('recordar');

        if (isset($_POST['Cliente']['correo_cliente'])) {
            $correo = $_POST['Cliente']['correo_cliente'];
            $model->attributes = $_POST['Cliente'];

            $model->validate("correo_cliente");

            $criteria = new CDbCriteria;
            $criteria->addCondition("correo_cliente = '" . $model->correo_cliente . "'");
            $criteria->addCondition('id_estado_usuario = 1');
            $envio = Cliente::model()->find($criteria);

            if ($envio) {
                $link = Yii::app()->createAbsoluteUrl("site/reset", array("m" => md5($envio->correo_cliente)));

                $message = '<p>Para restablecer su contraseña <a href="' . $link . '">Clic Aquí</a></p>';

                if ($_SERVER["SERVER_NAME"] == "localhost") {
                    dump($message);
                    Yii::app()->user->setFlash('warning', '<p>El sistema esta instalado en una maquina local y no se envia correo. </p>' . $message);
                } else {
                    $headers = "From: {" . Yii::app()->params['adminEmail'] . "}\r\nReply-To: {" . Yii::app()->params['adminEmail'] . "}";
                    mail($envio->correo_cliente, "Recuperar contraseña", $message, $headers);
                }
            } else {
                Yii::app()->user->setFlash('error', 'El correo no se encuentra registrado');
            }
        }
        $this->render('recordar', array("model" => $model));
    }

    public function actionReset() {
        $this->pageTitle = "Recuperar contraseña - " . YII::app()->name;

        $m = $_GET["m"];
        $clientes = Cliente::model()->findAll();
        foreach ($clientes as $value) {
            if (md5($value->correo_cliente) == $m) {
                $id_cliente = $value->id_cliente;
                $model = Cliente::model()->findByPk($id_cliente);
                $model->contrasena_cliente = "";
                if (isset($_POST['Cliente'])) {
                    $model->attributes = $_POST['Cliente'];
                    if ($model->contrasena_cliente === $model->repetir_contrasena) {
                        $model->contrasena_cliente = md5($model->contrasena_cliente);
                        if ($model->save()) {
                            Yii::app()->user->setFlash('success', "Se actualizaron los datos correctamente");
                            $this->redirect(array('site/login'));
                        }
                    } else {
                        Yii::app()->user->setFlash('error', "Las contraseñas no coinciden");
                        $this->render('reset', array("model" => $model));
                    }
                } else {
                    $this->render('reset', array("model" => $model));
                }
                break;
            }
        }
//        $this->render('reset');
    }

    /**
     * Displays the contact page
     */
    public function actionContact() {
        $model = new ContactForm;
        if (isset($_POST['ContactForm'])) {
            $model->attributes = $_POST['ContactForm'];
            if ($model->validate()) {
                $identificacionemail = "<p>" . $model->body . "</p>";

                $headers = "From: {$model->email}\r\nReply-To: {$model->email}";
                mail(Yii::app()->params['adminEmail'], $model->subject, $model->body, $headers);
                Yii::app()->user->setFlash('contact', 'Thank you for contacting us. We will respond to you as soon as possible.');
                $this->refresh();
            }
        }
        $this->render('contact', array('model' => $model));
    }

    public function actionRegistro() {
        $model = new Cliente('registro');
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Cliente'])) {
            $fecha = date_create()->format('Y-m-d H:i:s');
            $model->attributes = $_POST['Cliente'];
            $model->contrasena_cliente = md5($model->contrasena_cliente);
            $model->fecha_creacion_cliente = $fecha;
            $model->id_estado_usuario = 1;
            if ($model->save()) {
                $this->redirect(array('login', 'id' => $model->id_cliente));
            }
        }
        $model->contrasena_cliente = "";
        $this->render('registro', array(
            'model' => $model,
        ));
    }

    /**
     * Displays the login page
     */
    public function actionLogin() {
        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login()) {
                if (isset($_GET[0]['r'])) {
                    $return = $_GET[0]['r'];
                    $this->redirect($return);
                } else {
                    $this->redirect(Yii::app()->user->returnUrl);
                }
//                $this->redirect($current);
            }
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }

    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'cliente-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

front/protected/views/site/contact.php
<?php
$this->pageTitle = Yii::app()->name . ' - Contact Us';
$this->breadcrumbs = array(
    'Contact',
);
?>

<h1>Contacto</h1>



<div class="contact">
    <div class="contact-in">

        <div class=" col-md-9 contact-left">
            <?php if (Yii::app()->user->hasFlash('contact')): ?>

                <div class="flash-success">
                    <?php echo Yii::app()->user->getFlash('contact'); ?>
                </div>

            <?php else: ?>

                <?php
                $form = $this->beginWidget('CActiveForm', array(
                    'id' => 'contact-form',
                    'enableClientValidation' => true,
                    'clientOptions' => array(
                        'validateOnSubmit' => true,
                    ),
                ));
                ?>


                <?php // echo $form->errorSummary($model); ?>

                <div class="row">
                    <span><?php echo $form->labelEx($model, 'name'); ?></span>
                    <?php echo $form->textField($model, 'name'); ?>
                    <?php echo $form->error($model, 'name'); ?>
                </div>

                <div class="row">
                    <span><?php echo $form->labelEx($model, 'email'); ?></span>
                    <?php echo $form->textField($model, 'email', array("class" => "textbox")); ?>
                    <?php echo $form->error($model, 'email'); ?>
                </div>

                <div class="row">
                    <span><?php echo $form->labelEx($model, 'telefono'); ?></span>
                    <?php echo $form->textField($model, 'telefono', array("class" => "textbox")); ?>
                    <?php echo $form->error($model, 'telefono'); ?>
                </div>

                <div class="row">
                    <span><?php echo $form->labelEx($model, 'subject'); ?></span>
                    <?php echo $form->textField($model, 'subject', array('size' => 60, 'maxlength' => 128)); ?>
                    <?php echo $form->error($model, 'subject'); ?>
                </div>

                <div class="row">
                    <span><?php echo $form->labelEx($model, 'body'); ?></span>
                    <?php echo $form->textArea($model, 'body', array('rows' => 6, 'cols' => 50)); ?>
                    <?php echo $form->error($model, 'body'); ?>
                </div>

                <?php if (CCaptcha::checkRequirements()): ?>
                    <div class="row">
                        <?php echo $form->labelEx($model, 'verifyCode'); ?>
                        <div>
                            <?php $this->widget('CCaptcha'); ?>
                            <?php echo $form->textField($model, 'verifyCode'); ?>
                        </div>
                        <div class="hint">Please enter the letters as they are shown in the image above.
                            <br/>Letters are not case-sensitive.</div>
                        <?php echo $form->error($model, 'verifyCode'); ?>
                    </div>
                <?php endif; ?>

                <div class="row buttons">
                    <?php echo CHtml::submitButton('Enviar'); ?>
                </div>

                <?php $this->endWidget(); ?>

            <?php endif; ?>


        </div>

        <div class=" col-md-3 contact-right">
            <h5>Informacion de la Compañia</h5>
            <p>Calle 52 2 BIS - 15.</p>
            <p>Cali, Valle del Cauca</p>
            <p>Colombia</p>
            <p>Telefono:(+57) 317 2429481</p>
            <p>Fax: (000) 000 00 00 0</p>
            <p>Email: adsi150sena@hotmail.com</p>

        </div>
        <div class="clearfix"></div>
    </div>

    <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3982.5142527725707!2d-76.50278443480822!3d3.46744625207933!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e30a7cb4223ea99%3A0x60b26f8a8c3496eb!2sCentro+De+Electricidad+Y+Automatizaci%C3%B3n+Industrial+(C.E.A.I)!5e0!3m2!1ses!2sco!4v1540166292612" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>

front/protected/views/site/error.php
<?php
$this->pageTitle = Yii::app()->name . ' - Error';
$this->breadcrumbs = array(
    'Error',
);
?>
<div class="col-md-12">
     <h1>Error <?php echo $code; ?></h1>

    <div class="error">
        <?php echo CHtml::encode($message); ?>
    </div>
</div>

front/protected/views/site/index.php
<div class="women-in">

    <div class="col-md-9  col-xs-12 no-gutter">

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Carousel indicators -->
            <?php
            $cont = 0;
            $li = "";
            $itemsCarousel = "";
            ?>
            <ol class="carousel-indicators">
                <?php
                foreach ($promo as $promocion) {
                    if ($promocion->posicion_promocion == 1) {
                        if ($cont == 0) {
                            $class = "active";
                        }
                        echo '<li data-target="#myCarousel" data-slide-to="' . $cont . '"  class="' . $class . '"></li>';
                        $itemsCarousel = $itemsCarousel . '<div class="item ' . $class . '">
                            <a href="' . $promocion->enlace_promocion . '">'
                                . '<img src="' . $this->rutaImagen  . $promocion->imagen_promocion . '" alt="' . $promocion->id_promocion . '">
                            </a>
                            </div>';
                        $cont++;
                        $class = "";
                    }
                }
                ?>
            </ol>   
            <!-- Wrapper for carousel items -->
            <div class="carousel-inner">
                <?php echo $itemsCarousel; ?>
            </div>
            <!-- Carousel controls -->
            <a class="carousel-control left" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="carousel-control right" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>


        <div class="in-line">
            <div class="para-an">
                <h3>Temporada de descuentos!</h3>
                <p>Consulte nuestros últimos productos en esta sección.</p>
            </div>
            <div class="lady-in">
                <?php
                foreach ($productos as $value) {
                    echo '<div class="col-md-4 you-para">
                    <a href="' . Yii::app()->controller->createUrl("productos/VerProducto", array("c" => Helper::createurlSlug($value->idCategoria->nombre_categoria), "p" => Helper::createurlSlug($value->nombre_producto), "id" => $value->id_producto)) . '">
                        <img class="img-responsive pic-in" src="' . $this->rutaImagen . $value->imagen_producto . '" alt=" " ></a>
                    <p>' . ucfirst($value->nombre_producto) . '</p>
                    <span>' . Helper::separarMiles($value->precio_salida_producto) . '  | <label class="cat-in"> </label> <a href="#" class="add-to-cart" data-nombre="' . $value->nombre_producto . '"   data-id="' . $value->id_producto . '" >Añadir al carrito</a></span>
                </div>';
                }
                ?>

                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-xs-12">
        <?php
        $cont = 0;
        $pos2 = "";
        $pos3 = "";
        foreach ($promo as $promocion) {
            if ($promocion->posicion_promocion == 2) {
                $pos2 = '<a href="' . $promocion->enlace_promocion . '"><img class="img-responsive pic-in" src="' . $this->rutaImagen . $promocion->imagen_promocion . '" alt=" " >	</a>
                        <a href="' . $promocion->enlace_promocion . '" class="know-more">Conocer Más</a>';
                break;
            }

            if ($promocion->posicion_promocion == 3) {
                $pos3 = '<a href="' . $promocion->enlace_promocion . '"><img class="img-responsive pic-in" src="' . $this->rutaImagen . $promocion->imagen_promocion . '" alt=" " >	</a>
                        <a href="' . $promocion->enlace_promocion . '" class="know-more">Conocer Más</a>';
                break;
            }
        }
        if ($pos2 != "") {
            echo '<div class="discount">' . $pos2 . '</div>';
        }
        if ($pos3 != "") {
            echo '<div class="discount">' . $pos3 . '</div>';
        }
        ?>

        <!--        <div class="discount">
                    <a href="single.html"><img class="img-responsive pic-in" src="<?php echo Yii::app()->request->baseUrl; ?>/images/p3.jpg" alt=" " ></a>			
                <p class="no-more no-get">Obtiene<b>descuentos exclusivos </b> <span>en ropa para mujer</span></p>					
                <a href="#" class="know-more">Ver más</a>
            </div>-->
        <div class="twitter-in">
            <a class="twitter-timeline" data-lang="es" data-height="300" href="https://twitter.com/SENAComunica?ref_src=twsrc%5Etfw">Tweets by SENAComunica</a> 
            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

        </div>
    </div>
    <div class="clearfix"> </div>
</div>
<!---->

front/protected/views/site/login.php
<h1>Iniciar sesion</h1>


<div class="form clearfix" style="margin-bottom: 3em">
    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'login-form',
        'enableClientValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
        ),
    ));
    ?>


    <div class="col-md-6 text-center col-md-offset-3">
        <?php echo $form->labelEx($model, 'username'); ?>
        <?php echo $form->textField($model, 'username', array("class"=>"form-control")); ?>
        <?php echo $form->error($model, 'username'); ?>
    </div>

    <div class="col-md-6 text-center col-md-offset-3">
        <?php echo $form->labelEx($model, 'password'); ?>
        <?php echo $form->passwordField($model, 'password', array("class"=>"form-control")); ?>
        <?php echo $form->error($model, 'password'); ?>
    </div>

    <div class="col-md-6 text-center col-md-offset-3" style="margin-top: .0.5em">
        <?php echo CHtml::submitButton('Entrar', array("class"=>"btn btn-success")); ?>
    </div>

<?php $this->endWidget(); ?>
    <div class="clearfix"></div>
</div><!-- form -->

<div class="col-md-6 text-center col-md-offset-3" style="margin-bottom: 2em">
    <a href="<?php echo Yii::app()->controller->createUrl("site/recordarpass"); ?>" >¿Olvido la contraseña?</a>
    </div>

front/protected/views/site/privacidad.php
<div class="privacy-top">
    <h3>PRIVACIDAD</h3>

    <div class="privacy-bottom">

        <p ALIGN="justify">El presente Política de Privacidad establece los términos en que SISPROVA usa y protege la información que es proporcionada por sus usuarios al momento de utilizar su sitio web. Esta compañía está comprometida con la seguridad de los datos de sus usuarios. Cuando le pedimos llenar los campos de información personal con la cual usted pueda ser identificado, lo hacemos asegurando que sólo se empleará de acuerdo con los términos de este documento. Sin embargo esta Política de Privacidad puede cambiar con el tiempo o ser actualizada por lo que le recomendamos y enfatizamos revisar continuamente esta página para asegurarse que está de acuerdo con dichos cambios.</p>

        <div class="privacy-bottom">
            <h5><a href="#">Información que es recogida.</a></h5>
            <p ALIGN="justify">Nuestro sitio web podrá recoger información personal por ejemplo: Nombre,  información de contacto como  su dirección de correo electrónica e información demográfica. Así mismo cuando sea necesario podrá ser requerida información específica para procesar algún pedido o realizar una entrega o facturación.</p>
        </div>
        <div class="privacy-bottom">
            <h5><a href="#">Uso de la información recogida.</a></h5>
            <p ALIGN="justify">Nuestro sitio web emplea la información con el fin de proporcionar el mejor servicio posible, particularmente para mantener un registro de usuarios, de pedidos en caso que aplique, y mejorar nuestros productos y servicios.  Es posible que sean enviados correos electrónicos periódicamente a través de nuestro sitio con ofertas especiales, nuevos productos y otra información publicitaria que consideremos relevante para usted o que pueda brindarle algún beneficio, estos correos electrónicos serán enviados a la dirección que usted proporcione y podrán ser cancelados en cualquier momento.</p>
            <p ALIGN="justify">SISPROVA está altamente comprometido para cumplir con el compromiso de mantener su información segura. Usamos los sistemas más avanzados y los actualizamos constantemente para asegurarnos que no exista ningún acceso no autorizado.</p>
        </div>
        <div class="privacy-bottom">
            <h5><a href="#">Cookies</a></h5>
            <p ALIGN="justify">Una cookie se refiere a un fichero que es enviado con la finalidad de solicitar permiso para almacenarse en su ordenador, al aceptar dicho fichero se crea y la cookie sirve entonces para tener información respecto al tráfico web, y también facilita las futuras visitas a una web recurrente. Otra función que tienen las cookies es que con ellas las web pueden reconocerte individualmente y por tanto brindarte el mejor servicio personalizado de su web.</p>
            <p ALIGN="justify">Nuestro sitio web emplea las cookies para poder identificar las páginas que son visitadas y su frecuencia. Esta información es empleada únicamente para análisis estadístico y después la información se elimina de forma permanente. Usted puede eliminar las cookies en cualquier momento desde su ordenador. Sin embargo las cookies ayudan a proporcionar un mejor servicio de los sitios web, estás no dan acceso a información de su ordenador ni de usted, a menos de que usted así lo quiera y la proporcione directamente. Usted puede aceptar o negar el uso de cookies, sin embargo la mayoría de navegadores aceptan cookies automáticamente pues sirve para tener un mejor servicio web. También usted puede cambiar la configuración de su ordenador para declinar las cookies. Si se declinan es posible que no pueda utilizar algunos de nuestros servicios.</p>
        </div>
        <div class="privacy-bottom">
            <h5><a href="#">Enlaces a Terceros</a></h5>
            <p ALIGN="justify">Este sitio web pudiera contener en laces a otros sitios que pudieran ser de su interés. Una vez que usted de clic en estos enlaces y abandone nuestra página, ya no tenemos control sobre al sitio al que es redirigido y por lo tanto no somos responsables de los términos o privacidad ni de la protección de sus datos en esos otros sitios terceros. Dichos sitios están sujetos a sus propias políticas de privacidad por lo cual es recomendable que los consulte para confirmar que usted está de acuerdo con estas.</p>
        </div>
        <div class="privacy-bottom">
            <h5><a href="#">Control de su información personal</a></h5>
            <p ALIGN="justify">En cualquier momento usted puede restringir la recopilación o el uso de la información personal que es proporcionada a nuestro sitio web.  Cada vez que se le solicite rellenar un formulario, como el de alta de usuario, puede marcar o desmarcar la opción de recibir información por correo electrónico.  En caso de que haya marcado la opción de recibir nuestro boletín o publicidad usted puede cancelarla en cualquier momento.</p>
            <p ALIGN="justify">Esta compañía no venderá, cederá ni distribuirá la información personal que es recopilada sin su consentimiento, salvo que sea requerido por un juez con un orden judicial.</p>
            <p ALIGN="justify">SISPROVA Se reserva el derecho de cambiar los términos de la presente Política de Privacidad en cualquier momento.</p>
        </div>
    </div>
</div>

front/protected/views/site/recordar.php
<style>
    .errorMessage{ width:100% }
</style>
<h1>Iniciar sesion</h1>
<?php if (Yii::app()->user->hasFlash('error')) { ?>
    <div class="col-md-12 flash-error alert alert-error fade in alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
        <?php echo Yii::app()->user->getFlash('error'); ?>
    </div>
<?php } ?>
<?php if (Yii::app()->user->hasFlash('warning')) { ?>
    <div class="col-md-12 flash-warning alert alert-warning fade in alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
        <?php echo Yii::app()->user->getFlash('warning'); ?>
    </div>
<?php } ?>

<div class="form clearfix" style="margin-bottom: 3em">
    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'email-form',
        'enableClientValidation' => false,
        'clientOptions' => array(
            'validateOnSubmit' => false,
        ),
    ));
    ?>

    <div class="col-md-6 text-center col-md-offset-3">
        <?php echo $form->labelEx($model, 'correo_cliente'); ?>
        <?php echo $form->textField($model, 'correo_cliente', array("class" => "form-control", "required"=>"required")); ?>
        <?php echo $form->error($model, 'correo_cliente'); ?>
    </div>


    <div class="col-md-6 text-center col-md-offset-3" style="margin-top: 1em">
        <?php echo CHtml::submitButton('Enviar', array("class" => "btn btn-success")); ?>
    </div>

    <?php $this->endWidget(); ?>
    <div class="clearfix"></div>
</div><!-- form -->

front/protected/views/site/registro.php
<h1>Registro</h1>


<div class="register">

    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'cliente-form',
        'enableAjaxValidation' => false,
    ));
    ?>
    <div class="register-top-grid">
        <h3>INFORMACION PERSONAL</h3>

        <?php echo $form->errorSummary($model); ?>

        <div class="mation">
            <span><?php echo $form->labelEx($model, 'document_cliente'); ?></span>
            <?php echo $form->textField($model, 'document_cliente', array('size' => 50, 'maxlength' => 50)); ?>
            <?php echo $form->error($model, 'document_cliente'); ?>

            <span> <?php echo $form->labelEx($model, 'id_tipo_documento'); ?></span>
            <?php echo $form->dropDownList($model, 'id_tipo_documento', CHtml::listData(TipoDocumento::model()->findAll(), 'id_tipo_documento', 'nombre_tipo_documento'), array('empty' => 'Tipo de documento', 'class' => "form-controll")); ?>
            <?php echo $form->error($model, 'id_tipo_documento'); ?>

            <span> <?php echo $form->labelEx($model, 'empresa_cliente'); ?></span>
            <?php echo $form->textField($model, 'empresa_cliente', array('size' => 50, 'maxlength' => 50)); ?>
            <?php echo $form->error($model, 'empresa_cliente'); ?>


            <span><?php echo $form->labelEx($model, 'nombre_repre_cliente'); ?></span>
            <?php echo $form->textField($model, 'nombre_repre_cliente', array('size' => 50, 'maxlength' => 50)); ?>
            <?php echo $form->error($model, 'nombre_repre_cliente'); ?>

            <span> <?php echo $form->labelEx($model, 'apellido_repre_cliente'); ?></span>
            <?php echo $form->textField($model, 'apellido_repre_cliente', array('size' => 50, 'maxlength' => 50)); ?>
            <?php echo $form->error($model, 'apellido_repre_cliente'); ?>

            <span>  <?php echo $form->labelEx($model, 'telefono_cliente'); ?></span>
            <?php echo $form->textField($model, 'telefono_cliente', array('size' => 50, 'maxlength' => 50)); ?>
            <?php echo $form->error($model, 'telefono_cliente'); ?>

            <span><?php echo $form->labelEx($model, 'direccion_cliente'); ?></span>
            <?php echo $form->textField($model, 'direccion_cliente', array('size' => 50, 'maxlength' => 50)); ?>
            <?php echo $form->error($model, 'direccion_cliente'); ?>
            
            <span><?php echo $form->labelEx($model, 'id_ciudad'); ?></span>
            <?php echo $form->dropDownList($model, 'id_ciudad', CHtml::listData(Ciudad::model()->findAll(), 'id_ciudad', 'nombre_ciudad'), array('empty' => 'Seleccione ciudad', 'class' => "form-controll")); ?>
            <?php echo $form->error($model, 'id_ciudad'); ?>

            <span><?php echo $form->labelEx($model, 'correo_cliente'); ?></span>
            <?php echo $form->textField($model, 'correo_cliente', array('size' => 50, 'maxlength' => 50)); ?>
            <?php echo $form->error($model, 'correo_cliente'); ?>

            <span> <?php echo $form->labelEx($model, 'contrasena_cliente'); ?></span>
            <?php echo $form->passwordField($model, 'contrasena_cliente', array('size' => 60, 'maxlength' => 60)); ?>
            <?php echo $form->error($model, 'contrasena_cliente'); ?>
            
            <span> <?php echo $form->labelEx($model, 'repetir_contrasena'); ?></span>
            <?php echo $form->passwordField($model, 'repetir_contrasena', array('size' => 60, 'maxlength' => 60)); ?>
            <?php echo $form->error($model, 'repetir_contrasena'); ?>
            


            <div class="clearfix"> </div>
            <a class="news-letter" href="#">
                <label class="checkbox"><input type="checkbox" required name="checkbox" ><i> </i>Acepto los terminos y condiciones de uso.</label>
            </a>
            
            

            <div class="row buttons">
                <?php echo CHtml::submitButton('Registrarse', array("class"=>"btn btn-success") ); ?>
            </div>
        </div>

        <?php $this->endWidget(); ?>

    </div>
</div>